# system modes example
---

actuation:
  ros__parameters:
    type: system
    parts:
      drive_base
      left/manipulator
      right/manipulator
    modes:
      __DEFAULT__:
        drive_base: active
        left/manipulator: inactive
        right/manipulator: active.WEAK
      MODERATE:
        drive_base: active.SLOW
        left/manipulator: active.WEAK
        right/manipulator: active.WEAK
      PERFORMANCE:
        drive_base: active.FAST
        left/manipulator: active.STRONG
        right/manipulsator: active.STRONG

left/manipulator:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          max_torque: 0.1
      WEAK:
        ros__parameters:
          max_torque: 0.1
      STRONG:
        ros__parameters:
          max_torque: 0.2

drive_base:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          max_speed: 0.1
          controller: PID
      SLOW:
        ros__parameters:
          max_speed: 0.2
          controller: PID
      FAST:
        ros__parameters:
          max_speed: 0.9
          controller: MPC

right/manipulator:
  ros__parameters:
    type: node
    modes:
      __DEFAULT__:
        ros__parameters:
          max_torque: 0.11
      WEAK:
        ros__parameters:
          max_torque: 0.05
      STRONG:
        ros__parameters:
          max_torque: 0.3
