name: Lint system modes
on:
  pull_request:

jobs:
  ament_xmllint:
    name: ament_xmllint
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.0.25
    - uses: ros-tooling/action-ros2-lint@0.0.6
      with:
        linter: xmllint
        package-name: system_modes system_modes_examples

  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.0.25
    - uses: ros-tooling/action-ros2-lint@0.0.6
      with:
        linter: ${{ matrix.linter }}
        package-name: system_modes system_modes_examples

  ament_lint_py:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        linter: [flake8, pep257]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.0.25
    - uses: ros-tooling/action-ros2-lint@0.0.6
      with:
        linter: ${{ matrix.linter }}
        package-name: system_modes system_modes_examples
